set-option -sa terminal-overrides ",xterm*:Tc"
bind -n M-H previous-window
bind -n M-L next-window
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# style
set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'fg=color7 bg=default'
set -g status-right ''
set -g status-left '#S'
set -g status-left-style 'fg=color8'
set -g status-right-length 0
set -g status-left-length 100
setw -g window-status-current-style 'fg=colour6 bg=default bold'
setw -g window-status-current-format '#I:#W '
setw -g window-status-style 'fg=color8'

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.config/tmux/tmux.conf
bind c new-window -c "#{pane_current_path}"

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows
set-option -g renumber-windows on

run '~/.tmux/plugins/tpm/tpm'
