# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME

confirm_os_window_close 0

font_family      Source Code Pro
font_size 14

cursor_trail 3
cursor_trail_decay 0.1 0.2
