background {
    monitor =
    path = screenshot

    blur_passes = 2
    blur_size = 5
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

general {
    hide_cursor = true
}

input-field {
    monitor =
    size = 12%, 3%
    inner_color = rgba(0, 0, 0, 0.3)
    outline_thickness = 2

    dots_size = 0.25
    dots_spacitg = 0.55
    dots_rounding = -1

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 0
    placeholder_text =

    halign = center
    valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(240, 240, 240, 0.75)
  font_size = 20
  font_family = Noto Sans Bold
  position = 0, 405
  halign = center
  valign = center
}

label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%k:%M")"
  color = rgba(240, 240, 240, 0.75)
  font_size = 93
  font_family = Noto Sans Bold
  position = 0, 310
  halign = center
  valign = center
}
